export interface MessageData {
  group?: any;
  id?:any;
  type?: any;
  messagetype?: any;
  message?: any;
  time?: any;
  name?: any;
  isopen?: any;
  mobileNo?: any;
  fromId?:any;
  assignedto?:any;
  locationLatitude?:any;
  locationLongitude?:any;
  messageId?:any;
  messageStatus?:any;
  templateName?:any;
  templatePreview?:any;
  templateBody?:any;
  templateBodyAttributes?:any;
  templateHeader?:any;
  templateHeaderFileType?:any;
  templateHeaderfileLink?:any;
  templateButton1?:any;
  templateButton2?:any;
  templateButton3?:any;
  fileUrl?:any;
  notes?:any;
  username?:any;
  filename?:any;
}
